// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// app/layout.js
import React from 'react';
import './globals.css'; // Import global styles (optional)

export const metadata = {
  title: 'Admin Dashboard',
  description: 'Manage your users, roles, and permissions',
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <head>
        {/* You can add meta tags, links, and other head content here */}
      </head>
      <body className="bg-gray-100 text-gray-900">
        {/* This is where your page content will be rendered */}
        {children}
      </body>
    </html>
  );
};

export default RootLayout;

